version: '3'
services:
  back:
    container_name: back
    image: markstav/valerkino-back:latest
    environment:
      - "TOKEN=${TOKEN}"
      - "CHAT_ID=${CHAT_ID}"
      - "PORT=8085"
    expose:
      - "8085"
    restart: always
    networks:
      - app-network
  front:
    container_name: front
    image: markstav/valerkino-front:latest
    environment:
      - "NUXT_HOST=localhost"
      - "BACKEND_HOST=back"
      - "NUXT_PORT=4000"
      - "BACKEND_PORT=8085"
    expose:
      - "4000"
    restart: always
    command: 'npm dev'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge